name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    name: Build and publish
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock
          python-version: "3.13"

      - run: uv sync

      - run: uv build

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
